extends: ../train/e1_cmfo.yaml
experiment_name: cmfo_e1_b1_point_transformer
data:
  image_resolutions: [24]
  image_layouts: [regular]
model:
  name: b1_point_transformer
  node_layout: regular
train:
  consistency_weight: 0.0

